spring.datasource.url=jdbc:h2:mem:lumora
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=9999

lumora.jwt.secret=BnDGw/8yqw/d0dIx/dhEtmN4N/ZwS6Ur/3ZvVjSC0F/0xLYOR9f2k21IfLI9IeZwaXDnBy3uXqXqcORnaYPdxg==
lumora.jwt.expiration-ms=3600000

logging.level.org.springframework.security=DEBUG
logging.level.com.lumora=DEBUG

spring.web.resources.static-locations=classpath:/static/